export default [
  { id: 1, name: 'apache 2.0' },
  { id: 2, name: 'mit' },
  { id: 3, name: 'cc-by-sa-3.0' },
  { id: 4, name: 'afl-3.0' },
  { id: 5, name: 'cc-by-sa-4.0' },
  { id: 6, name: 'lgpl-3.0' },
  { id: 7, name: 'lgpl-lr' },
  { id: 8, name: 'cc-by-nc-3.0' },
  { id: 9, name: 'lgpl' },
  { id: 10, name: 'bsd-2-clause' },
  { id: 11, name: 'ecl-2.0' },
  { id: 12, name: 'cc-by-nc-sa-4.0' },
  { id: 13, name: 'cc-by-nc-4.0' },
  { id: 14, name: 'gpl-3.0' },
  { id: 15, name: 'other' },
  { id: 16, name: 'cc0-1.0' },
  { id: 17, name: 'cc' },
  { id: 18, name: 'bsd-3-clause' },
  { id: 19, name: 'agpl-3.0' },
  { id: 20, name: 'gpl' },
  { id: 21, name: 'wtfpl' },
  { id: 22, name: 'artistic-2.0' },
  { id: 23, name: 'postgresql' },
  { id: 24, name: 'bigscience-bloom-rail-1.0' },
  { id: 25, name: 'gpl-2.0' },
  { id: 26, name: 'isc' },
  { id: 27, name: 'bsd-3' },
  { id: 28, name: 'eupl-1.1' },
  { id: 29, name: 'academic free license v3.0' },
  { id: 30, name: 'pddl' },
  { id: 31, name: 'bsd-3-clause-clear' },
  { id: 32, name: 'mpl-2.0' },
];
export const trainSdk = [{ id: 1, name: 'ModelArts' }];
export const inferSdk = [
  { id: 1, name: 'Gradio' },
  { id: 2, name: 'Static' },
];
export const projectPhoto = [
  {
    id: 1,
    url: 'https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/project-img/proimg1.png',
    is_active: true,
  },
  {
    id: 2,
    url: 'https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/project-img/proimg2.png',
    is_active: false,
  },
  {
    id: 3,
    url: 'https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/project-img/proimg3.png',
    is_active: false,
  },
  {
    id: 4,
    url: 'https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/project-img/proimg4.png',
    is_active: false,
  },
];
